name: FaceTagger Unit Test

on:
  pull_request:
    branches:
      - develop


jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest tests/face_tagger_unit_test.py