name: FaceTagger E2E Test

on:
  push:
    branches:
      - release


jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    - name: Run e2e tests
      run: |
        pytest tests/face_tagger_e2e_test.py